### ISSUE TITLE
MQTT Errors

### ISSUE THREAD

**Issue by PurelyNicole** [PurelyNicole/Home-AssistantConfig#34]
Several MQTT errors in log.

```
Fri Mar 23 2018 09:26:14 GMT-0400 (Eastern Daylight Time)

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/mqtt/__init__.py", line 590, in _async_perform_subscription
    _raise_on_error(result)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/mqtt/__init__.py", line 676, in _raise_on_error
    'Error talking to MQTT: {}'.format(mqtt.error_string(result_code)))
homeassistant.exceptions.HomeAssistantError: Error talking to MQTT: The client is not currently connected.
```
Possibly related?
```
Fri Mar 23 2018 09:24:42 GMT-0400 (Eastern Daylight Time)

Error doing job: Fatal read error on socket transport
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 723, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
```

**Comment by PurelyNicole** [comment]
Eric fix
